apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false
 
    processors:
      - add_cloud_metadata:

    fields:
      kubernetes_cluster: citred2
      env: LOCAL
      plataform: MICROSERVICES
      plataform_type: POD
 
    setup:
      template:
        #name: "<CLUSTER_NAME>-%{[beat.version]}"
        name: "filebeat-%{[beat.version]}"
        #pattern: "<CLUSTER_NAME>-*"
        #pattern: "filebeat-*"
      #dashboards:
        #index: "<CLUSTER_NAME>-*"
        #index: "filebeat-via-logstash-*"
      kibana:
        #hosts: https://kibana.domain.com
        #host: http://kibana:5601
      #settings:
      #  index.number_of_shards: 1
      #  index.codec: best_compression

    output.logstash:
      hosts: ['logstash:5044'] 
kind: ConfigMap
metadata:
  labels:
    app: filebeat
  name: filebeat-config
  namespace: elastic-logging
---
apiVersion: v1
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      ignore_older: 72h
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
kind: ConfigMap
metadata:
  labels:
    app: filebeat
  name: filebeat-inputs
  namespace: elastic-logging