apiVersion: v1
data:
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw==
  ELASTICSEARCH_PASSWORD: "YnJhZGVzYzA="
  ELASTICSEARCH_HOST: "ZWxhc3RpY3NlYXJjaA=="
  ELASTICSEARCH_PORT: "OTIwMA=="
  ELASTICSEARCH_SCHEME: "aHR0cA=="
kind: Secret
metadata:
  name: kibana-creds
  namespace: elastic-logging
type: Opaque
 