apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elastic-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_HOST
                name: kibana-creds
          - name:  FLUENT_ELASTICSEARCH_PORT
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_PORT
                name: kibana-creds
          - name: FLUENT_ELASTICSEARCH_SCHEME
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_SCHEME
                name: kibana-creds
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
            value: fluentd-via-elasticsearch
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
            value: fluentd-via-elasticsearch
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
            value: "true"
          - name: FLUENT_ELASTICSEARCH_USER
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_USERNAME
                name: kibana-creds
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_PASSWORD
                name: kibana-creds        
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers