apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic-logging
  labels:
    app: logstash
    version: "1.0"
    environment: logging
spec:
  type: LoadBalancer
  externalIPs:
    - 172.17.0.3
  selector:
    app: logstash
    version: "1.0"
    environment: logging
  ports:
  - port: 5044
    targetPort: 5044