filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/tux.log
  document_type: logback  
  #multiline.pattern: ^\d\d\d\d
  #multiline.pattern: '^\['
  #multiline.negate: true
  #multiline.match: after
  fields:
    level: debug
    review: 1
    app: core
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
name: Java APP
tags: ["JAVA-X", "web-tier"]
fields:
  env: staging
setup.kibana:
output.logstash:
  hosts: ["172.17.0.3:5044"]
processors:
  - add_host_metadata: ~
logging.level: debug
